- sysctl: name=net.bridge.bridge-nf-call-ip6tables value=1 state=present reload=yes sysctl_set=yes
- sysctl: name=net.bridge.bridge-nf-call-iptables value=1 state=present reload=yes sysctl_set=yes

- name: fetch kubeadm-join from master
  command: cat /etc/kubeadm-join.sh
  register: cat_kubeadm_join
  when: inventory_hostname == master_hostname

- name: kubeadm join nodes
  shell: >
     systemctl stop kubelet ; kubeadm reset ; 
     echo "{{hostvars[master_hostname].cat_kubeadm_join.stdout}}" >/etc/kubeadm-join.sh ; 
     bash /etc/kubeadm-join.sh
  args:
    creates: /etc/kubeadm-join.sh
  when: inventory_hostname != master_hostname